### Obtener todas las fichas
GET http://localhost:8000/Ficha

### Crear una ficha
POST http://localhost:8000/Ficha
Content-Type: application/json

{
  "codigo": "hh",
  "fecha_inicio_lectiva": "20215-08-01",
  "fecha_fin_lectiva": "20126-01-31",
  "fecha_fin_practica": "21026-03-30",
  "programa_idprograma": 1
}

### Actualizar una ficha
PUT http://localhost:8000/Ficha
Content-Type: application/json

{
  "idficha": 1,
  "codigo": "FICHA002-CTUALIZADA",
  "fecha_inicio_lectiva": "2025-09-01",
  "fecha_fin_lectiva": "2024-02-28",
  "fecha_fin_practica": "2026-04-15",
  "programa_idprograma": 1
}

### Eliminar una ficha
DELETE http://localhost:8000/Ficha/3