### Obtener todas las fichas
GET http://localhost:8000/Ficha

### Crear una ficha
POST http://localhost:8000/Ficha
Content-Type: application/json

{
  "codigo": "cris",
  "fecha_inicio_lectiva": "2245-08-01",
  "fecha_fin_lectiva": "2016-01-31",
  "fecha_fin_practica": "2026-03-30",
  "programa_idprograma": 1
}

### Actualizar una ficha
PUT http://localhost:8000/Ficha
Content-Type: application/json

{
  "idficha": 2,
  "codigo": "FICHA002 sdadcha,as",
  "fecha_inicio_lectiva": "2025-09-01",
  "fecha_fin_lectiva": "2024-02-28",
  "fecha_fin_practica": "2026-04-15",
  "programa_idprograma": 1
}

### Eliminar una ficha
DELETE http://localhost:8000/Ficha/8