### Obtener todos los instructores
GET http://localhost:8000/Instructores

### Crear un instructor
POST http://localhost:8000/Instructor
Content-Type: application/json

{
  "nombre": "cris",
  "apellido": "Garcías",
  "email": "cris.garcias@sena.edu.co",
  "telefono": "3216549870"
}

### Actualizar un instructor
PUT http://localhost:8000/Instructor
Content-Type: application/json

{
  "idinstructor": 8,
  "nombre": "cristina",
  "apellido": "garcia",
  "email": "cris.R@sena.edu.co",
  "telefono": "3201234567"
}

### Eliminar un instructor
DELETE http://localhost:8000/Instructor/8