GET http://localhost:8000/profesiones

###
POST http://localhost:8000/profesion
Content-Type: application/json

{
    "nombre_profesion":"ING"
}

###
PUT http://localhost:8000/profesion
Content-Type: application/json

{
  "idprofesion": "3",
  "nombre_profesion": "Diseño Gráfico"
}

###
DELETE  http://localhost:8000/profesion/4