GET http://localhost:8000/programas

###
POST http://localhost:8000/programa
Content-Type: application/json

{
    "nombre_programa":"ADSO"
}

###
PUT http://localhost:8000/programa
Content-Type: application/json

{
    "idprograma":"2",
    "nombre_programa":"Aso noche"
}