### APRENDIZ
GET http://localhost:8000/Aprendiz

### FICHA
GET http://localhost:8000/Ficha

###
POST http://localhost:8000/Aprendiz
Content-Type: application/json

{
  "codigo": "FICHA001",
  "fecha_inicio_lectiva": "2025-07-01",
  "fecha_fin_lectiva": "2025-12-15",
  "fecha_fin_practica": "2026-01-30",
  "programa_idprograma": "1"
}

###

PUT http://localhost:8000/Aprendiz
Content-Type: application/json

{
  "idaprendiz":"4",
  "nombre":"cr7",
  "apellido":"sdf",
  "email":"jcddd@gmail.com",
  "telefono":"41243111"
}


###

DELETE  http://localhost:8000/Aprendiz/1

### PROGRAMA
